#!/usr/bin/env bash

declare -g text=''
declare -g attrs=''

appendAttr() {
    local newAttr="$1"
    if [[ -z $attrs ]]; then
        attrs="$newAttr"
    else
        attrs="${attrs} ${newAttr}"
    fi
}

selectionText() {
    tmux send-keys -X copy-selection \; show-buffer \; delete-buffer
}

isClick() {
    if [[ "$(tmux display-message -p '#{selection_present}')" = 0 ]]; then
        return 0
    fi
    local sel="$(selectionText)"
    if (( ${#sel} <= 1 )); then
        return 0
    fi
    return 1
}

plumbSelectionText() {
    text="$(selectionText)"
}

plumbClick() {
    local prefixText="$(tmux \
        send-keys -X begin-selection \; \
        send-keys -X previous-space \; \
        send-keys -X copy-selection \; \
        show-buffer \; \
        delete-buffer)"
    text="$(tmux \
        send-keys -X begin-selection \; \
        send-keys -X next-space \; \
        send-keys -X -N 2 cursor-left \; \
        send-keys -X copy-selection \; \
        show-buffer \; \
        delete-buffer)"
    local click="${#prefixText}"
    click=$(( click - 1 ))
    appendAttr "click=${click}"
}

main() {
    if isClick; then
        plumbClick
    else
        plumbSelectionText
    fi

    local workingDir="$(tmux display-message -p '#{pane_current_path}')"
    local -a command=( 9 plumb -s tmux -w "$workingDir" -a "$attrs" "$text" )
    local errors="$("${command[@]}" 2>&1)"
    if (( $? != 0 )); then
        tmux display-message -- "$errors"
    fi
}

main "$@"
