#!/usr/bin/env bash

declare -g text=''
declare -g attrs=''

appendAttr() {
    local newAttr="$1"
    if [[ -z $attrs ]]; then
        attrs="$newAttr"
    else
        attrs="${attrs} ${newAttr}"
    fi
}

haveSelection() {
    [[ "$(tmux display-message -p '#{selection_present}')" = 1 ]]
}

plumbSelectionText() {
    text="$(tmux \
        send-keys -X copy-selection \; \
        show-buffer \; \
        delete-buffer)"
}

plumbCurrentWORD() {
    local prefixText="$(tmux \
        send-keys -X begin-selection \; \
        send-keys -X previous-space \; \
        send-keys -X cursor-right \; \
        send-keys -X copy-selection \; \
        show-buffer \; \
        delete-buffer)"
    text="$(tmux \
        send-keys -X begin-selection \; \
        send-keys -X next-space \; \
        send-keys -X -N 2 cursor-left \; \
        send-keys -X copy-selection \; \
        show-buffer \; \
        delete-buffer)"
    local click="${#prefixText}"
    click=$(( click - 1 ))
    appendAttr "click=${click}"
}

main() {
    if haveSelection; then
        plumbSelectionText
    else
        plumbCurrentWORD
    fi

    errors=$(9 plumb -s tmux -a "$attrs" "$text" 2>&1)
    if (( $? != 0 )); then
        tmux display-message -- "$errors"
    fi
}

main "$@"
